name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Crud app build and push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: suprimi4/crud-app:latest


#  push_compose:
#    name: Push docker-compose.yaml to remote server
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Copy docker-compose.yml to server
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "docker-compose.yml"
#          target: ${{ secrets.TARGET_PATH }}